### PR TITLE
updated dependencies to support upstart and mysql_chef_game

### PR DESCRIPTION
**Pull request by tevren**
I updated a few things:
1. Using msyql_chef_gem instead of chef_gem as per recommendations on the database cookbook. This resulted in upgrading the version of database and mysql cookbooks.
2. Support upstart, this can be set via default['artifactory'][init_service'], default is set to runit.
3. Set mysql and artifactory database passwords via an encrypted data bag. 
4. updated Gemfile and Rakefile

### CODE REVIEW

**Comment by nicgrayson** [comment]
We don't use the cookbook anymore but this looks solid.

**Comment by xbeta** [comment]
this merge has few issues, which I've already highlighted.

@nicgrayson if you guys don't maintain it anymore, would you mind my company "github.com/lookout" taking this over as the base?

**Comment by nicgrayson** [comment]
@xbeta sounds like a good idea. I'll transfer it.

**Comment by nicgrayson** [comment]
@xbeta i'll add you to our org for just this repo so you can transfer it. https://help.github.com/articles/transferring-a-repository/#transferring-between-organizations

**Comment by xbeta** [comment]
@nicgrayson actually the owner of my current company's (github.com/lookout) github account belongs to @rtyler
Can you add him too?

**Comment by nicgrayson** [comment]
@xbeta done

**Comment by rtyler** [comment]
@nicgrayson @xbeta It looks like I have the necessary permissions, but since we have a fork of this repository in our organization we'll have to shuffle some things around on our end before GitHub will allow us to complete the operation.

I'll work with @xbeta when he gets in today to clear this up

**Comment by rtyler** [comment]
@nicgrayson all done moving, thanks!

**Pull request merged**
